name: to test
on:
  push:
    branches:
      master
env:
  MY_NAME: "Mantra"
jobs:
  my_first_job:
    if: github.repository == 'M-Anilkumar/testing'
    runs-on: ubuntu-latest
    needs: my_second_job
    steps:
      - name: Checkout code 
        uses: actions/checkout@v2
      - name: printing1
        run: echo "This is $MY_NAME"
  my_second_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # checking our the code at current commit that triggers the workflow
        uses: actions/checkout@v2
      - name: printing2
        run: echo "Hello everyone"
